<Project>
  <PropertyGroup>
    <!-- Default game install paths for Windows and macOS -->
    <GameDir Condition="'$(OS)' == 'Windows_NT' and '$(GameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\PolygonBitBattleRoyale</GameDir>
    <GameDir Condition="'$(OS)' != 'Windows_NT' and '$(GameDir)' == ''">$(HOME)/Library/Application Support/Steam/steamapps/common/PolygonBitBattleRoyale</GameDir>
    <BepInExDir>$(GameDir)\BepInEx</BepInExDir>
  </PropertyGroup>
</Project>
