<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>AccessibilityMod</AssemblyName>
    <RootNamespace>AccessibilityMod</RootNamespace>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameDir)\PolygonBitBattleRoyale_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameDir)\PolygonBitBattleRoyale_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(GameDir)\PolygonBitBattleRoyale_Data\Managed\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>$(GameDir)\PolygonBitBattleRoyale_Data\Managed\PhotonUnityNetworking.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>$(GameDir)\PolygonBitBattleRoyale_Data\Managed\PhotonRealtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameDir)\PolygonBitBattleRoyale_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GameDir)\PolygonBitBattleRoyale_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(GameDir)\PolygonBitBattleRoyale_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
